### PR TITLE
notebook: loading validation results

### PR DESCRIPTION
**Pull request by machow**
@hunterowens here's a quick notebook that does a little wrangling of the gtfs-validator results we have stored into DataFrames. There are 4 main DFs here:

* `status` - one row per agency x url
* `tidy_gtfs_files` - for successfully unzipped gtfs data, one row per file (including validation.json)
* `tidy_notice_codes` - one row per "code" in the validator results. A code is a type of violation. E.g. "invalid_phone_number".
* `tidy_notice_details` - one row per specific code violation (e.g. each missing phone number)

It's been useful for seeing which codes pop up most often, and I'm guessing we'll need to do a lot of detective work around codes to figure out which gtfs datasets we can load and how!

### CODE REVIEW

**Comment by machow** [comment]
Note that I used http://github.com/machow/siuba, since it fixes a couple pandas quirks that tend to slow me down (e.g. pandas does not have a grouped .assign method), but it's pretty quick to translate to plain pandas once I finish analyses / at the end of the day these kinds of transformations are sometimes better to do in the warehouse w/ SQL.

**Comment by hunterowens** [comment]
oooh nice! 

I think a good follow up PR might be allowing somebody to download these or select agencies using `ipywidgets` and do some basic data exploration. + #4

**Comment by machow** [comment]
Ah, good point--running this in dashboard setup should work okay, since it doesn't take too long to execute! Once we get a better handle on this data, we can chuck it into the airflow -> storage or the warehouse, so people don't have to wait for it to run

**Comment by hunterowens** [comment]
merging, refactor these tidy df into tables in bigquery in `data-infra`

**Pull request merged**
